apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextjs-microsite-test
  namespace: nextjs-microsite-test
  labels:
    app.kubernetes.io/name: nextjs-microsite-test
    app.kubernetes.io/managed-by: platform-engineering
